# Site settings
title: Darwin Biler
header-img: img/8110831512_9c19e7d3cc_k.jpg
email: darwin@bilersolutions.com
description: "Freelance PHP Developer / DevOps"
baseurl: ""
url: "https://www.darwinbiler.com"
twitter_username: darwinbiler
github_username:  buonzz
facebook_username: darwin.biler

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: [jekyll-paginate]