# Site settings
title: Darwin Biler
header-img: img/8110831512_9c19e7d3cc_k.jpg
email: darwin@buonzz.com
description: "Freelance PHP Developer / DevOps"
baseurl: ""
url: "http://www.darwinbiler.com"
twitter_username: buonzz
github_username:  buonzz
facebook_username: darwin.biler

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
