# Site settings
title: Darwin Biler's Blog
email: darwin@buonzz.com
description: Freelance Web Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://buonzz.github.io" # the base hostname & protocol for your site
twitter_username: buonzz
github_username:  buonzz

# Build settings
markdown: kramdown
