# Site settings
title: Darwin Biler
homepage-video: img/darwinbiler-com_compressed.mp4
default-banner-img: img/pexels-cookiecutter-37730212.jpg
email: buonzz@gmail.com
description: "Senior Backend Developer"
baseurl: ""
url: "https://www.darwinbiler.com"
twitter_username: darwinbiler
github_username:  buonzz
facebook_username: darwin.biler

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: [jekyll-paginate]